config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true
  belongs_to :project
  has_one :project_activities
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, :description, presence: true
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :comments
  belongs_to :admin_user
  has_many :project_activities,dependent: :destroy

  enum status: {
  unassigned: 'unassigned',
  pending: 'pending',
  accepted: 'accepted',
  started: 'started',
  completed: 'completed'
}, _suffix: true
end

app/models/project_activity.rb
class ProjectActivity < ApplicationRecord
  belongs_to :comment, optional: true
  belongs_to :admin_user
  belongs_to :project

  enum change_type: {
    comment: 'comment',
    status: 'status',
    comment_and_status: 'comment_and_status'
  }, _suffix: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/projects/_project_activities.html.erb
<div class="panel_contents charges-table">
  <table border="0" cellspacing="0" cellpadding="0">
    <thead>
      <tr>
        <th class="col">Created at</th>
        <th class="col">Change type</th>
        <th class="col">Updated by</th>
        <th class="col">Status</th>
        <th class="col">Comment</th>
      </tr>
    <thead>
    <tbody>
      <% resource.project_activities.each do |activity| %>
        <tr>
          <td class="col"><b><%= activity.created_at %></b></td>
          <td class="col"><b><%= activity.change_type.humanize %></b></td>
          <td class="col"><b><%= link_to activity.admin_user.email, admin_admin_user_path(id: activity.admin_user.id) %></b></td>
          <td class="col"><%= activity.status %></td>
          <td class="col"><%= activity.comment.body if activity.comment.present? %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectUserActivity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>